import {
  FaApple,
  FaDiscord,
  FaTwitter,
  FaBell,
  FaCrown,
  FaHand,
  FaMoon,
  FaPizzaSlice,
  FaRocket,
} from "react-icons/fa6"

import { BsCupHot, BsCurrencyDollar, BsFire } from "react-icons/bs"
import {
  BiAnchor,
  BiSolidBabyCarriage,
  BiSolidKey,
  BiSolidPlane,
  BiSolidTruck,
} from "react-icons/bi"

import { DiJsBadge } from "react-icons/di"

import {
  GiAlliedStar,
  GiAngularSpider,
  GiGhost,
  GiBootPrints,
  GiHalt,
  GiInjustice,
  GiMeal,
  GiOverkill,
  GiYinYang,
  GiWoodCabin,
} from "react-icons/gi"

import { GrAlarm, GrTrigger } from "react-icons/gr"

import {
  SiCounterstrike,
  SiFerrari,
  SiFoodpanda,
  SiFrontendmentor,
  SiGithub,
  SiHappycow,
  SiItunes,
  SiJordan,
  SiLichess,
  SiMailchimp,
  SiMamp,
  SiMeta,
  SiPlaywright,
  SiPremierleague,
  SiProtondb,
  SiRiotgames,
  SiTapas,
  SiTekton,
  SiTypescript,
  SiWindows10,
  SiYoutube,
} from "react-icons/si"

const icons = [
  BsCupHot,
  BsCurrencyDollar,
  BsFire,
  DiJsBadge,
  FaApple,
  FaDiscord,
  FaTwitter,
  FaBell,
  FaCrown,
  FaHand,
  FaMoon,
  FaPizzaSlice,
  FaRocket,
  GrAlarm,
  GrTrigger,
  SiCounterstrike,
  SiFerrari,
  SiFoodpanda,
  SiFrontendmentor,
  SiGithub,
  SiHappycow,
  SiItunes,
  SiJordan,
  SiLichess,
  SiMailchimp,
  SiMamp,
  SiMeta,
  SiPlaywright,
  SiPremierleague,
  SiProtondb,
  SiRiotgames,
  SiTapas,
  SiTekton,
  SiTypescript,
  SiWindows10,
  SiYoutube,
  GiAlliedStar,
  GiAngularSpider,
  GiGhost,
  GiBootPrints,
  GiHalt,
  GiInjustice,
  GiMeal,
  GiOverkill,
  GiYinYang,
  GiWoodCabin,
  BiAnchor,
  BiSolidBabyCarriage,
  BiSolidKey,
  BiSolidPlane,
  BiSolidTruck,
]

export { icons }
